[package]
name = "lab4ml"
version = "0.1.0"
authors = ["D. Kozlov <sprunk97@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
raster = "0.2.0"
clap = "2.33.0"
rand = "0.7.3"
libmath = "0.2.1"